sudo: required
services:
  - docker
after-success:
  - docker build -t akashoj/multi-client ./client
  - docker build -t akashoj/multi-server ./server
  - docker build -t akashoj/multi-worker ./worker
  - docker build -t akashoj/multi-nginx ./nginx